
services:
  mongodb:
    image: mongo:latest
    container_name: connecting-minds-db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - mongodb_network

networks:
  mongodb_network:

volumes:
  mongodb_data:
    driver: local